<a href="https://colab.research.google.com/github/sivasrivangapandu/sivasrivangapandu/blob/main/2x2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [16]:
import numpy as np
data=[[1,2,3],[4,5,6]]
arr=np.array(data)
arr
arr[:,1]


array([2, 5])

In [18]:
import numpy as np
data=[[1,2,3],[4,5,6],[7,8,9]]
arr=np.array(data)
arr[:2,1:]

array([[2, 3],
       [5, 6]])

In [25]:
import numpy as np
data=[[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]]
arr=np.array(data)
##transpose_arr=np.transpose(arr,(1,0,2))
transpose_arr=arr.swapaxes(0,1)
transpose_arr

array([[[1, 2, 3],
        [9, 8, 7]],

       [[4, 5, 6],
        [6, 5, 4]],

       [[7, 8, 9],
        [3, 2, 1]]])

In [30]:
import numpy as np
data=[[1,2,3],[4,5,6],[6,7,8]]
arr=np.array(data)
t_arr=arr.T
t_arr[-2,]


array([2, 5, 7])

In [47]:
import numpy as np
data=[[[1,2,3],[4,5,6],[7,8,9]],[[9,8,7],[6,5,4],[3,2,1]]]
arr=np.array(data)
arr[1][:2,1:]

array([[8, 7],
       [5, 4]])